export const COLUMNS = [
  { key: 'trialName',      label: 'Trial Name',      type: 'text',     width: 300, frozen: true },
  { key: 'contactEmail',   label: 'Contact Email',   type: 'text',     width: 180 },
  { key: 'contactPhone',   label: 'Contact Phone',   type: 'text',     width: 140 },
  { key: 'notes',          label: 'Notes',           type: 'textarea', width: 240 },
  { key: 'url',            label: 'URL',             type: 'url',      width: 200 },
  { key: 'status',         label: 'Contact Status',  type: 'select',   width: 160 },
  { key: 'treatmentType',  label: 'Treatment Type',  type: 'select',   width: 160 },
  { key: 'msTypeEligible', label: 'MS Type',         type: 'select',   width: 150 },
  { key: 'nctNumber',      label: 'NCT Number',      type: 'text',     width: 130 },
  { key: 'nearestSite',    label: 'Nearest Site',    type: 'text',     width: 280 },
  { key: 'keyCaveat',      label: 'Key Caveat',      type: 'textarea', width: 300 },
];

export const SELECT_OPTIONS = {
  priority: ['⭐⭐⭐ Top Priority', '⭐⭐ Strong Option', '⭐ Consider'],
  status: ['Not Contacted', 'Contacted', 'In Talks', 'Cancelled'],
  treatmentType: ['CAR-T Cell Therapy', 'HSCT / Stem Cell', 'Regulatory T Cell', 'Remyelination', 'Allogeneic CAR-T', 'BTK Inhibitor', 'Novel Biologic', 'Neuroprotection', 'Precision Medicine'],
  msTypeEligible: ['RRMS', 'Progressive', 'Any MS', 'Refractory/Relapsing'],
  location: ['USA 🇺🇸', 'China 🇨🇳', 'Europe 🇪🇺', 'International 🌍', 'Russia 🇷🇺', 'Taiwan 🇹🇼'],
};

export const BADGE_COLORS = {
  priority: {
    '⭐⭐⭐ Top Priority':  { bg: '#d1fae5', color: '#065f46', border: '#6ee7b7' },
    '⭐⭐ Strong Option':   { bg: '#dbeafe', color: '#1e40af', border: '#93c5fd' },
    '⭐ Consider':          { bg: '#fef9c3', color: '#854d0e', border: '#fde047' },
  },
  status: {
    'Not Contacted': { bg: '#f1f5f9', color: '#475569', border: '#cbd5e1' },
    'Contacted':     { bg: '#fef9c3', color: '#854d0e', border: '#fde047' },
    'In Talks':      { bg: '#dbeafe', color: '#1e40af', border: '#93c5fd' },
    'Cancelled':     { bg: '#fee2e2', color: '#991b1b', border: '#fca5a5' },
  },
  treatmentType: {
    'CAR-T Cell Therapy':   { bg: '#ede9fe', color: '#5b21b6', border: '#c4b5fd' },
    'HSCT / Stem Cell':     { bg: '#dbeafe', color: '#1e40af', border: '#93c5fd' },
    'Regulatory T Cell':    { bg: '#d1fae5', color: '#065f46', border: '#6ee7b7' },
    'Remyelination':        { bg: '#ffedd5', color: '#9a3412', border: '#fdba74' },
    'Allogeneic CAR-T':     { bg: '#fce7f3', color: '#9d174d', border: '#f9a8d4' },
    'BTK Inhibitor':        { bg: '#fee2e2', color: '#991b1b', border: '#fca5a5' },
    'Novel Biologic':       { bg: '#fef9c3', color: '#854d0e', border: '#fde047' },
    'Neuroprotection':      { bg: '#fef3c7', color: '#78350f', border: '#fcd34d' },
    'Precision Medicine':   { bg: '#f3f4f6', color: '#1f2937', border: '#9ca3af' },
  },
  msTypeEligible: {
    'RRMS':                 { bg: '#d1fae5', color: '#065f46', border: '#6ee7b7' },
    'Progressive':          { bg: '#ffedd5', color: '#9a3412', border: '#fdba74' },
    'Any MS':               { bg: '#dbeafe', color: '#1e40af', border: '#93c5fd' },
    'Refractory/Relapsing': { bg: '#ede9fe', color: '#5b21b6', border: '#c4b5fd' },
  },
};

let _id = 1;
const id = () => String(_id++);

export const INITIAL_DATA = [
  {
    id: id(), trialName: 'Frexalimab Phase III — Relapsing MS (Sanofi, 1600 patients)',
    priority: '⭐⭐⭐ Top Priority', status: 'Not Contacted', treatmentType: 'Novel Biologic',
    msTypeEligible: 'RRMS', location: 'USA 🇺🇸', nctNumber: 'NCT06141473', enrollment: '1600',
    startDate: '2023-12-13', nearestSite: 'Many US sites: CA, AL, AZ, CO, FL, IL, MI, MN, MO, NJ, NY, OH, TX and more',
    keyCaveat: 'Requires washout from Alemtuzumab (duration TBD). Comparator is teriflunomide. Must not have prior CD40L therapy. Many US sites available.',
    whyBetter: 'Anti-CD40L (CD154) biologic blocking co-stimulatory signal critical for T and B cell activation — novel mechanism not shared by any approved MS drug. Phase III with 1600 patients, Sanofi\'s largest MS trial. Selective immunomodulation rather than broad immune depletion.',
    url: 'https://clinicaltrials.gov/study/NCT06141473', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'BEAT-MS — Autologous HSCT vs Best Available Therapy',
    priority: '⭐⭐⭐ Top Priority', status: 'Not Contacted', treatmentType: 'HSCT / Stem Cell',
    msTypeEligible: 'RRMS', location: 'USA 🇺🇸', nctNumber: 'NCT04047628', enrollment: '156',
    startDate: '2019-12-19', nearestSite: 'Stanford MS Center, Palo Alto, CA (25 min from San Jose)',
    keyCaveat: 'Requires stopping Alemtuzumab (washout needed). Significant short-term risk (hospitalization, infection). Requires prior failure of 2+ DMTs — Shabnam qualifies.',
    whyBetter: 'HSCT essentially reboots the entire immune system — the only treatment shown to halt MS long-term with no ongoing therapy. Phase III randomized trial at Stanford, the same center that already reviewed Shabnam. Already mentioned in her Stanford note.',
    url: 'https://clinicaltrials.gov/study/NCT04047628', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'mRNA-1195 Tolerogenic Vaccine — MS Relapse Prevention (Moderna)',
    priority: '⭐⭐⭐ Top Priority', status: 'Not Contacted', treatmentType: 'Novel Biologic',
    msTypeEligible: 'RRMS', location: 'USA 🇺🇸', nctNumber: 'NCT06735248', enrollment: '180',
    startDate: '2025-04-16', nearestSite: 'Washington Univ. St. Louis MO | Boston MA | Quest Research Farmington Hills MI',
    keyCaveat: 'Age limit ≤55 (Shabnam is 28 ✓). Phase II, 180 participants. Novel mechanism with limited prior human data. May require washout from Alemtuzumab.',
    whyBetter: "Moderna's antigen-specific tolerogenic mRNA vaccine teaches the immune system to stop attacking myelin without global immunosuppression. Potentially curative mechanism unlike any current DMT. Could induce remission without ongoing immunosuppression.",
    url: 'https://clinicaltrials.gov/study/NCT06735248', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'KYV-101 Anti-CD19 CAR-T Therapy — Progressive MS',
    priority: '⭐⭐⭐ Top Priority', status: 'Not Contacted', treatmentType: 'CAR-T Cell Therapy',
    msTypeEligible: 'Progressive', location: 'USA 🇺🇸', nctNumber: 'NCT06138132', enrollment: '12',
    startDate: '2024-04-10', nearestSite: 'Stanford MS Center, Palo Alto, CA (25 min from San Jose)',
    keyCaveat: 'Currently recruiting for progressive forms of MS. Shabnam is RRMS but has progressive features — eligibility needs confirmation with Stanford. Requires lymphodepletion (chemo conditioning).',
    whyBetter: 'Single-infusion anti-CD19 CAR-T therapy that eliminates the autoreactive B cell pool at a much deeper level than Alemtuzumab. CAR-T in autoimmune disease has shown remarkable remissions in early data (lupus, myositis). Also at Stanford — same team that reviewed Shabnam.',
    url: 'https://clinicaltrials.gov/study/NCT06138132', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'Obe-cel (Obecabtagene Autoleucel) CAR-T — Refractory Progressive MS (Autolus/Stanford)',
    priority: '⭐⭐⭐ Top Priority', status: 'Not Contacted', treatmentType: 'CAR-T Cell Therapy',
    msTypeEligible: 'Progressive', location: 'USA 🇺🇸', nctNumber: 'NCT07139743', enrollment: '18',
    startDate: '2025-08-04', nearestSite: 'Stanford University, Redwood City, CA (30 min from San Jose)',
    keyCaveat: 'Currently for progressive/refractory forms. Shabnam is RRMS but has progressive features — confirm eligibility with Stanford. Requires lymphodepletion conditioning chemo.',
    whyBetter: 'Fast-off-rate anti-CD19 CAR-T by Autolus designed to reduce toxicity while achieving deep B cell depletion. Stanford site, Phase I for refractory progressive MS — Shabnam\'s profile. More targeted immune reset than Alemtuzumab.',
    url: 'https://clinicaltrials.gov/study/NCT07139743', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'CC-97540 CAR-T (BMS/Juno) — Relapsing & Progressive MS (Breakfree-2)',
    priority: '⭐⭐⭐ Top Priority', status: 'Not Contacted', treatmentType: 'CAR-T Cell Therapy',
    msTypeEligible: 'RRMS', location: 'USA 🇺🇸', nctNumber: 'NCT06220201', enrollment: '120',
    startDate: '2024-03-28', nearestSite: 'UC Irvine CA | Univ. of Colorado | Univ. of Alabama | Colorado Blood Cancer Institute',
    keyCaveat: 'Phase I — still establishing safety/tolerability. Requires lymphodepletion (fludarabine + cyclophosphamide). Alemtuzumab washout period likely needed.',
    whyBetter: "Bristol-Myers Squibb/Juno CAR-T covering both relapsing AND progressive MS forms. Phase I/II with strong US academic sites including CA. BMS/Juno's CAR-T oncology expertise now applied to autoimmune MS — deeper immune reset than Alemtuzumab.",
    url: 'https://clinicaltrials.gov/study/NCT06220201', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'Remibrutinib Phase III — Secondary Progressive MS (Novartis, 1275 patients)',
    priority: '⭐⭐⭐ Top Priority', status: 'Not Contacted', treatmentType: 'BTK Inhibitor',
    msTypeEligible: 'Progressive', location: 'USA 🇺🇸', nctNumber: 'NCT07225504', enrollment: '1275',
    startDate: '2025-11-11', nearestSite: 'CA (Fullerton), AZ, AL, CO, FL and many more US sites',
    keyCaveat: 'SPMS indication. Shabnam has RRMS with progressive features — confirm eligibility. BTK inhibitors require monitoring for infections/liver. Washout from Alemtuzumab needed.',
    whyBetter: 'Highly CNS-penetrant BTK inhibitor suppressing microglia and B cells inside the brain — targeting compartmentalized CNS inflammation that Alemtuzumab cannot reach. Completely new mechanism for MS. Phase III, 1275 patients, high rigor.',
    url: 'https://clinicaltrials.gov/study/NCT07225504', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'Remibrutinib Switch Study — After Anti-CD20, RRMS (Novartis, 360 patients)',
    priority: '⭐⭐⭐ Top Priority', status: 'Not Contacted', treatmentType: 'BTK Inhibitor',
    msTypeEligible: 'RRMS', location: 'USA 🇺🇸', nctNumber: 'NCT06846281', enrollment: '360',
    startDate: '2025-07-23', nearestSite: 'AZ, DC, FL, GA, IL, MA, MI, MN, NJ, NY, OH, TX, VA and more — many US sites',
    keyCaveat: 'Designed for patients switching FROM anti-CD20 (Shabnam\'s history). Must confirm if prior Alemtuzumab is acceptable. Requires washout period from Alemtuzumab.',
    whyBetter: 'BTK inhibitor switch-from-anti-CD20 trial for RRMS. Shabnam was on Ocrevus before Alemtuzumab — highly relevant background. CNS-penetrant BTK inhibition adds what anti-CD20 therapies miss. Oral daily vs infusions.',
    url: 'https://clinicaltrials.gov/study/NCT06846281', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'TRAP-MS Precision Biomarker-Guided Combination Therapy — MS (NIH/NIAID)',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'Precision Medicine',
    msTypeEligible: 'Any MS', location: 'USA 🇺🇸', nctNumber: 'NCT03109288', enrollment: '250',
    startDate: '2017-08-11', nearestSite: 'NIH Clinical Center, Bethesda, MD',
    keyCaveat: "NIH Bethesda MD requires travel. Best for patients with residual activity despite DMT — exactly Shabnam's situation. Multi-drug protocol is complex.",
    whyBetter: "Biomarker-guided combinations of repurposed drugs (pirfenidone, pioglitazone, cilostazol) targeting residual MS activity despite DMT — Shabnam's exact problem. NIH-sponsored precision medicine targeting what single DMTs including Alemtuzumab miss.",
    url: 'https://clinicaltrials.gov/study/NCT03109288', contactEmail: '', contactPhone: '', notes: 'Talked and got the information',
  },
  {
    id: id(), trialName: 'RO7121932 Novel Biologic — MS (Roche/Genentech, Stanford)',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'Novel Biologic',
    msTypeEligible: 'Any MS', location: 'USA 🇺🇸', nctNumber: 'NCT05704361', enrollment: '129',
    startDate: '2021-08-11', nearestSite: 'Stanford Medical Center, Stanford CA (20 min from San Jose!) | Yale CT | USF FL | UMass MA',
    keyCaveat: 'Phase I safety/PK focus. Stanford site means she may enroll through existing relationship with her care team there. Requires Alemtuzumab washout.',
    whyBetter: "Novel Roche/Genentech biologic in Phase I at Stanford — same team as Shabnam's care. Distinct mechanism from any approved DMT. Genentech's deep MS pipeline expertise. Stanford site means she can potentially enroll through Dr. Kipp's team.",
    url: 'https://clinicaltrials.gov/study/NCT05704361', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'AZD0120 Anti-BDCA2 Novel Biologic — MS (AstraZeneca)',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'Novel Biologic',
    msTypeEligible: 'Any MS', location: 'USA 🇺🇸', nctNumber: 'NCT07224373', enrollment: '24',
    startDate: '2025-12-09', nearestSite: 'AZ, CO, DC, MO, NY, OR — multiple US research sites',
    keyCaveat: 'Phase I/II, 24 participants, open-label. Early stage with limited prior human safety data. Washout from Alemtuzumab required.',
    whyBetter: 'Targets BDCA2 on plasmacytoid dendritic cells — a cell type driving CNS inflammation not targeted by any current MS drug. Novel upstream immunomodulation, more selective and potentially safer than broad immune depletion by Alemtuzumab.',
    url: 'https://clinicaltrials.gov/study/NCT07224373', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'P-CD19CD20-ALLO1 — Allogeneic Dual-Target CAR-T for MS',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'Allogeneic CAR-T',
    msTypeEligible: 'Any MS', location: 'USA 🇺🇸', nctNumber: 'NCT07008378', enrollment: '60',
    startDate: '2025-10-15', nearestSite: 'UC Irvine Gross Hall CIRM Stem Cell Center, 845 Health Sciences Rd, Irvine CA 92697 | UC San Diego Altman CTRI, 9452 Medical Ctr Dr, La Jolla CA 92037 | Washington University, St. Louis, MO',
    keyCaveat: 'Phase I safety trial — very early stage. Includes lymphodepletion chemo. Alemtuzumab washout period likely required. Now has CA sites at UC Irvine and UC San Diego.',
    whyBetter: 'Off-the-shelf (allogeneic) CAR-T targeting BOTH CD19 and CD20 simultaneously — broader and deeper B cell depletion than any approved DMT. No need to harvest patient\'s own cells (faster). Novel dual-target approach not possible with conventional therapy. CA sites now confirmed.',
    url: 'https://clinicaltrials.gov/study/NCT07008378',
    contactEmail: 'alphaclinic@hs.uci.edu',
    contactPhone: '(858) 534-1251',
    notes: 'UC Irvine: Sue & Bill Gross Stem Cell Research Center (Gross Hall CIRM), 845 Health Sciences Rd, Irvine CA 92697 — SCRCdirector@hs.uci.edu / alphaclinic@hs.uci.edu\nUC San Diego: Altman Clinical & Translational Research Institute, 9452 Medical Ctr Dr, La Jolla CA 92037 — (858) 534-1251',
  },
  {
    id: id(), trialName: 'Frexalimab Phase III — Non-Relapsing SPMS (Sanofi, 900 patients)',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'Novel Biologic',
    msTypeEligible: 'Progressive', location: 'USA 🇺🇸', nctNumber: 'NCT06141486', enrollment: '900',
    startDate: '2023-12-27', nearestSite: 'Many US sites: AZ, AL, CA, CO, FL, TX and more',
    keyCaveat: 'Non-relapsing SPMS only. Shabnam is RRMS — confirm eligibility via progressive features. Alemtuzumab washout required.',
    whyBetter: 'Same anti-CD40L mechanism for non-relapsing SPMS — hardest-to-treat subtype. Phase III 900 patients. Addresses CNS compartmentalized inflammation that Alemtuzumab cannot reach effectively.',
    url: 'https://clinicaltrials.gov/study/NCT06141486', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'Foralumab Nasal Spray Phase II — Non-Active SPMS (Brigham & Women\'s/Harvard)',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'Novel Biologic',
    msTypeEligible: 'Progressive', location: 'USA 🇺🇸', nctNumber: 'NCT06890923', enrollment: '55',
    startDate: '2025-03-04', nearestSite: "Brigham and Women's Hospital, Boston, MA",
    keyCaveat: 'Non-active SPMS only. Shabnam is RRMS — check if progressive features qualify. Small trial (55 patients), Phase II. Primary completion April 2026 — verify still enrolling.',
    whyBetter: 'Only fully human anti-CD3 antibody via nasal mucosal route — induces regulatory T cell tolerance without systemic immunosuppression. Pioneered at Harvard/BWH. No systemic immune depletion — potentially safer long-term than Alemtuzumab.',
    url: 'https://clinicaltrials.gov/study/NCT06890923', contactEmail: '', contactPhone: '', notes: 'Left VM',
  },
  {
    id: id(), trialName: 'Foralumab Nasal Phase II/III — Non-Active SPMS (Yale/JHU/BWH)',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'Novel Biologic',
    msTypeEligible: 'Progressive', location: 'USA 🇺🇸', nctNumber: 'NCT06292923', enrollment: '54',
    startDate: '2023-11-15', nearestSite: 'Yale CT | Johns Hopkins MD | Brigham & Women\'s MA | UMass | U Buffalo NY',
    keyCaveat: 'SPMS indication. Confirm if progressive features qualify Shabnam. Primary completion Nov 2025 — verify still enrolling. Alemtuzumab washout needed.',
    whyBetter: 'Larger foralumab nasal trial at Yale, JHU, BWH — top MS centers. Nasal anti-CD3 mucosal tolerance is fundamentally different and potentially safer than Alemtuzumab while addressing CNS-compartmentalized disease.',
    url: 'https://clinicaltrials.gov/study/NCT06292923', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'Remibrutinib MRI Sub-study — RRMS & SPMS (Cleveland Clinic)',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'BTK Inhibitor',
    msTypeEligible: 'RRMS', location: 'USA 🇺🇸', nctNumber: 'NCT07222956', enrollment: '20',
    startDate: '2026-04-01', nearestSite: 'Cleveland Clinic, Cleveland, OH',
    keyCaveat: 'Not yet recruiting. Small (20 patients) — fills quickly. Ohio requires travel. Washout from Alemtuzumab needed.',
    whyBetter: 'Open-label remibrutinib with detailed brain MRI endpoints for both RRMS and SPMS. Cleveland Clinic is a top MS center. RRMS eligible unlike most BTK trials. Allows direct measurement of CNS effects.',
    url: 'https://clinicaltrials.gov/study/NCT07222956', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'Frexalimab SC vs IV — Phase II PK/PD Study (Sanofi)',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'Novel Biologic',
    msTypeEligible: 'RRMS', location: 'USA 🇺🇸', nctNumber: 'NCT07325292', enrollment: '160',
    startDate: '2026-01-14', nearestSite: 'AL, AZ, CA, CO, CT, FL, IL, MI, MN, MO, NJ, NY, NC, OH, PA, TX and more',
    keyCaveat: 'PK/formulation study comparing SC vs IV frexalimab. Patients must qualify de novo for frexalimab. Washout from Alemtuzumab required. Small (160 patients).',
    whyBetter: 'Anti-CD40L mechanism — same novel MOA as the Phase III frexalimab trial. Access to frexalimab with detailed pharmacodynamic data collection. Selective co-stimulation blocker with potential superiority over broad immune depletion.',
    url: 'https://clinicaltrials.gov/study/NCT07325292', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'Orelabrutinib BTK Inhibitor — Secondary Progressive MS (Zenas, 990 patients)',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'BTK Inhibitor',
    msTypeEligible: 'Progressive', location: 'USA 🇺🇸', nctNumber: 'NCT07299019', enrollment: '990',
    startDate: '2026-03', nearestSite: 'Neurology Associates, Maitland, FL',
    keyCaveat: 'SPMS only currently. Shabnam has RRMS — confirm progressive eligibility. Limited US sites so far. More sites expected given 990-patient enrollment target.',
    whyBetter: 'CNS-penetrant BTK inhibitor targeting microglial and B cell activation inside the blood-brain barrier — the compartmentalized inflammation driving progressive MS that Alemtuzumab cannot address. Phase III, 990 patients.',
    url: 'https://clinicaltrials.gov/study/NCT07299019', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'Senolytics (Dasatinib + Quercetin) — Secondary Progressive MS (Ohio State)',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'Neuroprotection',
    msTypeEligible: 'Progressive', location: 'USA 🇺🇸', nctNumber: 'NCT07270120', enrollment: '30',
    startDate: '2026-01-15', nearestSite: 'Ohio State University, Columbus, OH',
    keyCaveat: 'SPMS only. Shabnam is RRMS — progressive features may qualify. Small trial (30 patients). Columbus OH requires travel.',
    whyBetter: 'Clears senescent cells accumulating in MS brains that drive neurodegeneration — entirely different mechanism from any DMT. Addresses aging/neurodegeneration in progressive MS that immunosuppression like Alemtuzumab cannot touch.',
    url: 'https://clinicaltrials.gov/study/NCT07270120', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'NLY01 GLP-1 Receptor Agonist — MS Neuroprotection (Johns Hopkins)',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'Neuroprotection',
    msTypeEligible: 'Any MS', location: 'USA 🇺🇸', nctNumber: 'NCT07497399', enrollment: '120',
    startDate: '2026-04', nearestSite: 'Johns Hopkins University, Baltimore, MD',
    keyCaveat: 'Phase II add-on. Primarily neuroprotective — not immunosuppressive replacement. JHU Baltimore site only. Best combined with existing DMT.',
    whyBetter: 'GLP-1 receptor agonist (related to semaglutide/Ozempic class) suppresses microglial activation in the CNS — addressing neurodegeneration that Alemtuzumab cannot. Targets non-inflammatory progressive MS mechanisms. Strong preclinical data.',
    url: 'https://clinicaltrials.gov/study/NCT07497399', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'Clemastine Fumarate Remyelination — RRMS/PPMS/SPMS (UCSF San Francisco)',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'Remyelination',
    msTypeEligible: 'Any MS', location: 'USA 🇺🇸', nctNumber: 'NCT05359653', enrollment: '74',
    startDate: '2023-08-01', nearestSite: 'UCSF Sandler Neurosciences, San Francisco, CA (45 min from San Jose!)',
    keyCaveat: 'Remyelination add-on, not a replacement for immunotherapy. RRMS/PPMS/SPMS all eligible. Very close to San Jose. Can likely be combined with current Alemtuzumab.',
    whyBetter: 'First proven remyelinating drug in humans. Repurposed antihistamine promoting oligodendrocyte maturation and myelin repair. Addresses disability already accumulated — something Alemtuzumab cannot do. UCSF is 45 min from San Jose.',
    url: 'https://clinicaltrials.gov/study/NCT05359653', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'SetPoint Vagus Nerve Stimulation — Pro-Remyelination in RRMS',
    priority: '⭐⭐ Strong Option', status: 'Not Contacted', treatmentType: 'Remyelination',
    msTypeEligible: 'RRMS', location: 'USA 🇺🇸', nctNumber: 'NCT06796504', enrollment: '60',
    startDate: '2026-03-31', nearestSite: 'Shepherd Center Atlanta GA | UW Medicine Seattle WA | Minnesota MS Center',
    keyCaveat: 'Requires surgical implant (minimally invasive). Add-on to existing DMTs, not a replacement. RRMS only. US sites: Atlanta GA, Seattle WA, Plymouth MN.',
    whyBetter: 'Vagus nerve stimulation promotes remyelination — repairing myelin damage rather than just stopping immune attacks. Addresses disability accumulation that no immunosuppressant including Alemtuzumab can reverse. Combines with existing DMT.',
    url: 'https://clinicaltrials.gov/study/NCT06796504', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'Orelabrutinib BTK Inhibitor — Primary Progressive MS (Zenas, 705 patients)',
    priority: '⭐ Consider', status: 'Not Contacted', treatmentType: 'BTK Inhibitor',
    msTypeEligible: 'Progressive', location: 'USA 🇺🇸', nctNumber: 'NCT07067463', enrollment: '705',
    startDate: '2025-12', nearestSite: 'Neurology Associates Maitland FL | Premier Neurology Greenville SC',
    keyCaveat: 'PPMS only. Shabnam has RRMS — confirm if progressive features allow enrollment. Limited US sites currently. Alemtuzumab washout required.',
    whyBetter: 'CNS-penetrant BTK inhibitor for PPMS. Addresses CNS compartmentalized disease. Phase III, 705 patients. Oral daily medication — simpler than Alemtuzumab infusion cycles.',
    url: 'https://clinicaltrials.gov/study/NCT07067463', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'Metformin Add-on for MS Neuroprotection (SUNY Buffalo)',
    priority: '⭐ Consider', status: 'Not Contacted', treatmentType: 'Neuroprotection',
    msTypeEligible: 'Any MS', location: 'USA 🇺🇸', nctNumber: 'NCT06463743', enrollment: '30',
    startDate: '2025-09-24', nearestSite: 'UBMD Neurology, Buffalo, NY',
    keyCaveat: 'Small trial (30 patients). Add-on — not a replacement for immunotherapy. Buffalo NY requires travel. More supportive than curative on its own.',
    whyBetter: 'Neuroprotective anti-aging AMPK activator with remyelination support effects. Addresses neurodegeneration that immunosuppression alone cannot stop. Can be used as add-on to existing Alemtuzumab treatment.',
    url: 'https://clinicaltrials.gov/study/NCT06463743', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'Clemastine Fumarate — Acute Demyelinating Lesions with MRI Endpoints (UCSF)',
    priority: '⭐ Consider', status: 'Not Contacted', treatmentType: 'Remyelination',
    msTypeEligible: 'Any MS', location: 'USA 🇺🇸', nctNumber: 'NCT06065670', enrollment: '44',
    startDate: '2026-09-15', nearestSite: 'UCSF Sandler Neurosciences, San Francisco, CA (45 min from San Jose!)',
    keyCaveat: 'Not yet recruiting (starts Sept 2026). Requires presence of active demyelinating lesion per MRI — eligibility depends on Shabnam\'s current imaging. Add-on, not replacement.',
    whyBetter: 'Targets acute demyelinating lesions with advanced MRI remyelination measurement. Repairs damage at the time it occurs — complementary to any immunotherapy. UCSF 45 min from San Jose.',
    url: 'https://clinicaltrials.gov/study/NCT06065670', contactEmail: '', contactPhone: '', notes: '',
  },
  {
    id: id(), trialName: 'KITE-363 Dual Anti-CD19/CD20 CAR-T — Relapsing & Progressive MS (Kite/Gilead)',
    priority: '⭐⭐⭐ Top Priority', status: 'Not Contacted', treatmentType: 'CAR-T Cell Therapy',
    msTypeEligible: 'Any MS', location: 'USA 🇺🇸', nctNumber: 'NCT07304154', enrollment: '52',
    startDate: '2026-04-10', nearestSite: 'LDS Hospital – Intermountain Health, Salt Lake City UT | Stanford (pending Dr. Lee) | Fred Hutchinson, Seattle WA',
    keyCaveat: 'Phase 1, only 52 patients — fills fast. Autologous CAR-T requires cell harvesting. Lymphodepletion chemo required. Also covers CIDP & Myasthenia Gravis. Stanford site confirmed but awaiting Dr. Lee response.',
    whyBetter: 'Kite/Gilead dual-target autologous CAR-T hitting both CD19 and CD20 simultaneously — deepest B cell depletion possible. Phase 1 basket trial across autoimmune neurologic diseases. Kite is the world leader in CAR-T manufacturing and safety.',
    url: 'https://clinicaltrials.gov/study/NCT07304154',
    contactEmail: 'medinfo@kitepharma.com',
    contactPhone: '385-282-2751',
    notes: '✅ Already contacted Dr. Timothy West — LDS Hospital Intermountain Health, Salt Lake City UT 84143. Also at Stanford — waiting for Dr. Lee to respond.',
  },
  {
    id: id(), trialName: 'KYV-101 Anti-CD19 CAR-T — Refractory Progressive MS (UCSF Single-Center)',
    priority: '⭐⭐⭐ Top Priority', status: 'Not Contacted', treatmentType: 'CAR-T Cell Therapy',
    msTypeEligible: 'Progressive', location: 'USA 🇺🇸', nctNumber: 'NCT06451159', enrollment: '10',
    startDate: '2024-06-01', nearestSite: 'UCSF MS & Neuroinflammation Center, 1651 4th St Suite 252, San Francisco, CA 94158 (~45 min from San Jose)',
    keyCaveat: 'Currently "Active, not recruiting" — only 10 patients, fills extremely fast. Progressive MS only; EDSS 3.0–7.0 required. Lymphodepletion chemo (cyclophosphamide + fludarabine) required. Ages 25–70.',
    whyBetter: 'UCSF-led autologous anti-CD19 CAR-T by Kyverna Therapeutics — deepest B cell depletion for progressive MS. Same UCSF MS center as Shabnam\'s care team (Dr. Bruce Cree). 45 min from San Jose. Earlier/smaller sister trial to the multi-site KYV-101 study.',
    url: 'https://clinicaltrials.gov/study/NCT06451159',
    contactEmail: '',
    contactPhone: '(415) 353-2069',
    notes: 'UCSF Multiple Sclerosis and Neuroinflammation Center — 1651 4th St Suite 252, San Francisco, CA 94158. PI: Dr. Bruce Cree.',
  },
  {
    id: id(), trialName: 'RESET-MS — CABA-201 Anti-CD19 CAR-T for Relapsing & Progressive MS (Cabaletta Bio)',
    priority: '⭐⭐⭐ Top Priority', status: 'Not Contacted', treatmentType: 'CAR-T Cell Therapy',
    msTypeEligible: 'Any MS', location: 'USA 🇺🇸', nctNumber: 'NCT07006805', enrollment: '12',
    startDate: '2026-06', nearestSite: 'Sites not yet listed — estimated start June 2026. Contact sponsor to be added to waitlist.',
    keyCaveat: 'Not yet recruiting — only 12 patients, will fill extremely fast. Ages 18–60 ✓. Prior high-efficacy therapy failure required (Shabnam qualifies). Prior alemtuzumab must be >1 year ago — confirm timing. Lymphodepletion chemo required.',
    whyBetter: 'Cabaletta Bio\'s CABA-201 autologous anti-CD19 CAR-T covers both relapsing AND progressive MS — one of the few trials open to all MS types. Phase 1/2. Same deep B cell depletion mechanism as other leading CAR-T trials. Getting on the waitlist now is critical given only 12 spots.',
    url: 'https://clinicaltrials.gov/study/NCT07006805',
    contactEmail: 'clinicaltrials@cabalettabio.com',
    contactPhone: '267-759-3100 ext. 4444',
    notes: '',
  },
  {
    id: id(), trialName: 'Azer-cel (Azercabtagene Zapreleucel) Allogeneic CAR-T — Progressive MS (TG Therapeutics)',
    priority: '⭐⭐⭐ Top Priority', status: 'Not Contacted', treatmentType: 'Allogeneic CAR-T',
    msTypeEligible: 'Progressive', location: 'USA 🇺🇸', nctNumber: 'NCT06680037', enrollment: '32',
    startDate: '2024-11', nearestSite: 'La Jolla, CA | Ann Arbor, MI | Cleveland & Columbus, OH | Omaha, NE | New York & Rochester, NY | Milwaukee, WI',
    keyCaveat: 'Progressive MS only (PPMS or SPMS). Shabnam is RRMS — confirm if progressive features qualify. Must have discontinued current DMT. No prior CAR-T therapy allowed. No malignancy within 2 years. Allogeneic (off-the-shelf) — no cell harvesting needed.',
    whyBetter: 'Off-the-shelf allogeneic anti-CD19 CAR-T by TG Therapeutics — no waiting to harvest patient\'s own cells, faster access. Phase 1 across 9 US sites with CA location (La Jolla). Targets B-cell driven progressive MS with a ready-made product. 32 patients — larger than most CAR-T trials.',
    url: 'https://clinicaltrials.gov/study/NCT06680037',
    contactEmail: 'clinicalsupport@tgtxinc.com',
    contactPhone: '1-877-575-8489',
    notes: 'TG Therapeutics Clinical Support Team.',
  },
];
